// <auto-generated />
namespace UniversityProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _005Course : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_005Course));
        
        string IMigrationMetadata.Id
        {
            get { return "201901251718412_005-Course"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
